import React from 'react'

const Travel = () => {
  return (
    <>
      <div className="travel-main ">
        <div className="travel-imgs">
          <img
            src="/javaacript-certificate.png"
            width={350}
            height={350}
            alt="travel"
          />
          <img
            src="/javaacript-certificate.png"
            width={350}
            height={350}
            alt="travel"
          />
          <img
            src="/javaacript-certificate.png"
            width={350}
            height={350}
            alt="travel"
          />
          <img
            src="/javaacript-certificate.png"
            width={350}
            height={350}
            alt="travel"
          />
          <img
            src="/javaacript-certificate.png"
            width={350}
            height={350}
            alt="travel"
          />

          <img
            src="/javaacript-certificate.png"
            width={350}
            height={350}
            alt="travel"
          />
          <img
            src="/javaacript-certificate.png"
            width={350}
            height={350}
            alt="travel"
          />
          <img
            src="/javaacript-certificate.png"
            width={350}
            height={350}
            alt="travel"
          />
          <img
            src="/javaacript-certificate.png"
            width={350}
            height={350}
            alt="travel"
          />
          <img
            src="/javaacript-certificate.png"
            width={350}
            height={350}
            alt="travel"
          />
          <img
            src="/javaacript-certificate.png"
            width={350}
            height={350}
            alt="travel"
          />

          <img
            src="/javaacript-certificate.png"
            width={350}
            height={350}
            alt="travel"
          />
          <img
            src="/javaacript-certificate.png"
            width={350}
            height={350}
            alt="travel"
          />
          <img
            src="/javaacript-certificate.png"
            width={350}
            height={350}
            alt="travel"
          />
          <img
            src="/javaacript-certificate.png"
            width={350}
            height={350}
            alt="travel"
          />
          <img
            src="/javaacript-certificate.png"
            width={350}
            height={350}
            alt="travel"
          />
        </div>
      </div>
    </>
  );
}

export default Travel
